# Generated by Django 6.1 on 2026-08-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
