/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/me/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['auth_me_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/signup/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_signup_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/token/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Takes a set of user credentials and returns an access and refresh JSON web
     *     token pair to prove the authentication of those credentials.
     */
    post: operations['auth_token_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/token/refresh/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     *     token if the refresh token is valid.
     */
    post: operations['auth_token_refresh_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/categories/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['categories_list'];
    put?: never;
    post: operations['categories_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/categories/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['categories_retrieve'];
    put: operations['categories_update'];
    post?: never;
    delete: operations['categories_destroy'];
    options?: never;
    head?: never;
    patch: operations['categories_partial_update'];
    trace?: never;
  };
  '/api/notes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['notes_list'];
    put?: never;
    post: operations['notes_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notes/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['notes_retrieve'];
    put: operations['notes_update'];
    post?: never;
    delete: operations['notes_destroy'];
    options?: never;
    head?: never;
    patch: operations['notes_partial_update'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Category: {
      /** Format: uuid */
      readonly id: string;
      name: string;
      color_hex?: string;
      /** Format: date-time */
      readonly created_at: string;
    };
    CategoryRequest: {
      name: string;
      color_hex?: string;
    };
    Note: {
      /** Format: uuid */
      readonly id: string;
      title: string;
      content?: string;
      readonly category: components['schemas']['Category'];
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    NoteRequest: {
      title: string;
      content?: string;
      /** Format: uuid */
      category_id?: string | null;
    };
    PatchedCategoryRequest: {
      name?: string;
      color_hex?: string;
    };
    PatchedNoteRequest: {
      title?: string;
      content?: string;
      /** Format: uuid */
      category_id?: string | null;
    };
    SignUp: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      email: string;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
    };
    SignUpRequest: {
      /** Format: email */
      email: string;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      password: string;
    };
    TokenObtainPair: {
      readonly access: string;
      readonly refresh: string;
    };
    TokenObtainPairRequest: {
      email: string;
      password: string;
    };
    TokenRefresh: {
      readonly access: string;
      refresh: string;
    };
    TokenRefreshRequest: {
      refresh: string;
    };
    User: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      readonly email: string;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      readonly username: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  auth_signup_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpRequest'];
        'application/x-www-form-urlencoded': components['schemas']['SignUpRequest'];
        'multipart/form-data': components['schemas']['SignUpRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignUp'];
        };
      };
    };
  };
  auth_token_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenObtainPairRequest'];
        'application/x-www-form-urlencoded': components['schemas']['TokenObtainPairRequest'];
        'multipart/form-data': components['schemas']['TokenObtainPairRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenObtainPair'];
        };
      };
    };
  };
  auth_token_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRefreshRequest'];
        'application/x-www-form-urlencoded': components['schemas']['TokenRefreshRequest'];
        'multipart/form-data': components['schemas']['TokenRefreshRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenRefresh'];
        };
      };
    };
  };
  categories_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'][];
        };
      };
    };
  };
  categories_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryRequest'];
        'application/x-www-form-urlencoded': components['schemas']['CategoryRequest'];
        'multipart/form-data': components['schemas']['CategoryRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
    };
  };
  categories_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this category. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
    };
  };
  categories_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this category. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryRequest'];
        'application/x-www-form-urlencoded': components['schemas']['CategoryRequest'];
        'multipart/form-data': components['schemas']['CategoryRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
    };
  };
  categories_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this category. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  categories_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this category. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedCategoryRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedCategoryRequest'];
        'multipart/form-data': components['schemas']['PatchedCategoryRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
    };
  };
  notes_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'][];
        };
      };
    };
  };
  notes_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NoteRequest'];
        'application/x-www-form-urlencoded': components['schemas']['NoteRequest'];
        'multipart/form-data': components['schemas']['NoteRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
    };
  };
  notes_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this note. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
    };
  };
  notes_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this note. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NoteRequest'];
        'application/x-www-form-urlencoded': components['schemas']['NoteRequest'];
        'multipart/form-data': components['schemas']['NoteRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
    };
  };
  notes_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this note. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  notes_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this note. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedNoteRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedNoteRequest'];
        'multipart/form-data': components['schemas']['PatchedNoteRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
    };
  };
}
